# This workflow will build and deploy a .NET project to GitHub Pages
# More info: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy .NET to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Necesario para hacer push al branch gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish -c Release -o output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN_ENTREGABLE8 }}
        publish_dir: ./output/wwwroot
        publish_branch: gh-pages  # Asegúrate que GitHub Pages esté configurado para usar esta rama
